import { SpeedInsights } from "@vercel/speed-insights/next";
import { AuthProvider } from "./contexts/AuthContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <SpeedInsights />
          <div>{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
